config/routes.rb
Rails.application.routes.draw do
  resources :content_blocks
  devise_for :users
  ActiveAdmin.routes(self)

  root to: "home#show"
  resources :rsvp, only: [:new]
  resources :guests, only: [:show, :update] do
    get 'search', on: :collection
  end

  # sign in
  get "/auth" => redirect("/users/sign_in")
  get "/login" => redirect("/users/sign_in")
  get "/signin" => redirect("/users/sign_in")

  # sign out
  get "/logout" => redirect("/signout")
  get "/signout" => "home#signout"

  # blazer for admins
  authenticate :user, ->(user) { user.is_admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  # review emails in development
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/GuestCategory.rb
class GuestCategory < ApplicationRecord
  has_many :guests
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true
end

app/models/ahoy/message.rb
class Ahoy::Message < ApplicationRecord
  self.table_name = "ahoy_messages"

  belongs_to :user, polymorphic: true, optional: true
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content_block.rb
class ContentBlock < ApplicationRecord
  has_paper_trail
  has_rich_text :content
  has_many_attached :images
  belongs_to :content_type
  belongs_to :page
end

app/models/content_type.rb
class ContentType < ApplicationRecord
  has_many :content_blocks
  default_scope { order("LOWER(name)") }
end

app/models/guest.rb
class Guest < ApplicationRecord
  include Hashid::Rails
  belongs_to :guest_category
  include PgSearch::Model
  pg_search_scope :search, against: [:name1, :name2, :email1, :email2]
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :content_blocks
  default_scope { order("LOWER(name)") }
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  has_paper_trail
  cache_prefix { "v1" }

  field :google_analytics_tracker, default: nil, type: :string
  field :automated_reminder_emails, default: true, type: :boolean
end

app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails
  default_scope { order("LOWER(first_name), LOWER(last_name)") }
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable
  has_many :messages, class_name: "Ahoy::Message", as: :user
  has_many :visits, class_name: "Ahoy::Visit"
  has_paper_trail
  scope :owners, -> { where(email: OWNER_EMAILS) }
  scope :not_owners, -> { where.not(email: OWNER_EMAILS) }
  scope :admin, -> { where(is_admin: true) }
  before_validation(on: :create) do
    # if no password, set random passwords on user
    self.password = SecureRandom.base64(16) if password.blank?
  end

  def authenticate(password)
    Devise::Encryptor.compare(User, encrypted_password, password)
  end

  def name
    [first_name, last_name].compact.join(" ").presence || email
  end

  def sort_key
    [last_name, email].compact.join(" ").downcase
  end

  #
  # vanity users
  #
  KYLE_EMAIL = "kyle.p.fritz@gmail.com"
  MEG_EMAIL = "meghan.l.ames@gmail.com"
  OWNER_EMAILS = [KYLE_EMAIL, MEG_EMAIL]
  def self.kyle
    User.find_by(email: KYLE_EMAIL)
  end

  def self.meg
    User.find_by(email: MEG_EMAIL)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  before_action :set_paper_trail_whodunnit
  before_action :authenticate_user!
  before_action :set_raven_context

  protected

  def set_raven_context
    Raven.user_context(id: current_user&.id, email: current_user&.email, is_admin: current_user&.is_admin)
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

  def user_for_paper_trail
    current_user&.id
  end

  def redirect_unless_user_is_admin!
    # used by active admin to keep out non-admins
    unless current_user&.is_admin?
      logger.info "redirect_unless_user_is_admin: its NOT ok"
      redirect_to "/", alert: "you must be an admin"
    end
  end

  def current_admin_user
    if current_user&.is_admin?
      current_user
    end
  end
end

app/controllers/concerns/user_hashidable.rb
module UserHashidable
  extend ActiveSupport::Concern

  included do
    skip_before_action :authenticate_user!
    before_action :require_hashid_user_or_devise_user!

    # we're going to change the definition of current_user
    # rename current_user to devise_user
    alias_method :devise_user, :current_user

    protected

    def current_user
      hashid_user || devise_user
    end

    def require_hashid_user_or_devise_user!
      if hashid_user
        logger.info "found user {#{hashid_user.name}} for hashid=#{hashid}"
      end

      unless current_user
        logger.info "womp no hashid; redirecting to login. params=#{params}"
        authenticate_user!
      end
    end

    def hashid
      params[:uid]
    end

    def hashid_user
      if hashid
        User.find_by_hashid(hashid)
      end
    end
  end
end

app/controllers/content_blocks_controller.rb
class ContentBlocksController < InheritedResources::Base

  private

    def content_block_params
      params.require(:content_block).permit(:page, :name, :content)
    end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate_user!

  def search
    @guests = Guest.search(params[:q])
    render formats: :json
  end

  def show
    @guest = Guest.find(params[:id])
    render formats: :json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @blocks = helpers.prep_blocks(ContentBlock.all.includes(:content_type))
    render "show", layout: params[:layout] || 'application'
  end

  def signout
    sign_out :user
    redirect_to "/"
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    render :new, layout: nil
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_block_helper.rb
module ContentBlockHelper
  def b(name)
    if @blocks.key?(name)
      @blocks[name].content
    else
      "Content \"#{name}\" is missing"
    end
  end
end

app/helpers/content_blocks_helper.rb
module ContentBlocksHelper

  def prep_blocks(blocks)
    ActiveSupport::HashWithIndifferentAccess.new([]).tap do |h|
      blocks.each do |block|
        key = block.content_type.name
        unless h.key?(key)
          h[key] = []
        end
        h[key].push(block)
      end
    end
  end

  # get content of a single block
  def content(name)
    block(name).content
  end

  # get a single block
  def block(name)
    list(name).first
  end

  # get a list of blocks
  def list(name)
    if @blocks.key?(name)
      @blocks[name]
    else
      [ContentBlock.new(content: "Create block <strong>#{name}</strong>")]
    end
  end
end

app/views/admin/content_blocks/_content.html.erb
<%= form_with(model: content_block, local: true, url: admin_content_block_path(content_block)) do |form| %>
  <% if content_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content_block.errors.count, "error") %> prohibited this content_block from being saved:</h2>

      <ul>
        <% content_block.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/content_blocks/_form.html.erb
<%= semantic_form_for [:admin, @content_block], builder: ActiveAdmin::FormBuilder do |f| %>
  <%= f.inputs :page, :content_type, :date, :title %>
  <%= f.file_field :images, multiple: true, direct_upload: true %>
  <%= f.actions %>
<% end %>

app/views/content_blocks/_form.html.erb
<%= form_with(model: content_block, local: true) do |form| %>
  <% if content_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content_block.errors.count, "error") %> prohibited this content_block from being saved:</h2>

      <ul>
        <% content_block.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :page %>
    <%= form.text_field :page %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/content_blocks/edit.html.erb
<h1>Editing Content Block</h1>

<%= render 'form', content_block: @content_block %>

<%= link_to 'Show', @content_block %> |
<%= link_to 'Back', content_blocks_path %>

app/views/content_blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Content Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @content_blocks.each do |content_block| %>
      <tr>
        <td><%= content_block.page %></td>
        <td><%= content_block.title %></td>
        <td><%= link_to 'Show', content_block %></td>
        <td><%= link_to 'Edit', edit_content_block_path(content_block) %></td>
        <td><%= link_to 'Destroy', content_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content Block', new_content_block_path %>

app/views/content_blocks/new.html.erb
<h1>New Content Block</h1>

<%= render 'form', content_block: @content_block %>

<%= link_to 'Back', content_blocks_path %>

app/views/content_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @content_block.page %>
</p>

<p>
  <strong>Title:</strong>
  <%= @content_block.title %>
</p>

<%= @content_block.content %>

<%= link_to 'Edit', edit_content_block_path(@content_block) %> |
<%= link_to 'Back', content_blocks_path %>

app/views/home/show.html.erb
<% if block(:Parallax)&.images&.first %>
<div class="parallax" style="background-image:url(<%= Rails.application.routes.url_helpers.rails_blob_path(block(:Parallax).images.first, only_path: true)%>)">
  <h1><%= block(:Parallax).title %></h1>
</div>
<div class="after-parallax" />
<% end %>

<h2>Events</h2>

<div class="row my-5 events">
  <% list(:Event).each do|block| %>
    <% block.images.each do |image| %>
    <div class="col">      
      <%= image_tag(image.representation(resize_to_limit: [500, 500]), alt: block.title, class: 'img-fluid', style: "object-fit:contain") %>
      <%= block.content %>

    </div>
    <% end %>
  <% end %>
</div>


<h2>History</h2>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl</p>

<div class="row my-5">
  <% list(:History)[10..11].each do|block| %>
    <% block.images.each do |image| %>
    <div class="col">
      <%= image_tag(image.representation(resize_to_limit: [500, 500]), alt: block.title, class: 'img-fluid', style: "object-fit:contain") %>
    </div>
    <% end %>
  <% end %>
</div>

<div class="row py-5 darker-background">
  <% list(:History)[12..20].each do|block| %>

    <div class="col-4 px-5 my-4">
      <h3><%= block.title %></h3>
      <%= block.content %>
    </div>

  <% end %>
</div>

<div id="react" class="py-5"></div>
<%= javascript_pack_tag 'camp' %>

<div class="row py-5 darker-background">
  <div class="col">
    <h2>mmmmmmm</h2>
    <div><%= content(:yo) %></div>
  </div>
</div>

app/views/rsvps/new.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RSVP for Deep Wedding</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <% if Setting.google_analytics_tracker.present? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= Setting.google_analytics_tracker %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', '<%= Setting.google_analytics_tracker %>');
  </script>
  <% end %>

  <%= stylesheet_link_tag 'rsvp', media: 'all'%>
  <%= include_gon(:camel_case => true, :camel_depth => :recursive) %>
</head>

<body class="container-fluid">
  <%= javascript_pack_tag 'camp' %>
  <div id="react" />

</body>
</html>

app/views/welcome/index.html.erb
<div class="splash-container">
    <div class="splash">
        <h1 class="splash-head">Deep Wedding</h1>
        <p class="splash-subhead">
            This is going to be so fun!
        </p>
        <p>
            <a class="pure-button pure-button-primary">West Virgina</a>
            <a class="pure-button pure-button-primary">New Jersey</a>
            <a class="pure-button pure-button-primary">DC</a>
        </p>
    </div>
</div>